version: "3.8"

services:
  # Base de datos MySQL para Cafés Marloy
  mysql:
    image: mysql:8.0
    container_name: cafes-marloy-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: Obligatorio
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_spanish_ci
    ports:
      - "3306:3306"
    volumes:
      # Montar el archivo SQL para inicializar la BD
      - ./Tablas.sql:/docker-entrypoint-initdb.d/01-tablas.sql:ro
      # Volumen persistente para los datos (opcional)
      - mysql_data:/var/lib/mysql
    networks:
      - cafes-marloy-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootroot",
        ]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 30s

  # Opcional: Adminer para administrar la BD vía web
  adminer:
    image: adminer:latest
    container_name: cafes-marloy-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - cafes-marloy-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local

networks:
  cafes-marloy-network:
    driver: bridge
